"""Added column tag to correios table

Revision ID: 2dfb9cef20de
Revises: 407689a9e91a
Create Date: 2021-06-24 11:17:09.542742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfb9cef20de'
down_revision = '407689a9e91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('tag', sa.String(), nullable=True))
    op.add_column('package', sa.Column('latest_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'latest_message_id')
    op.drop_column('package', 'tag')
    # ### end Alembic commands ###
