"""Added BDay and User table

Revision ID: 407689a9e91a
Revises: 
Create Date: 2021-03-18 22:59:44.942420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "407689a9e91a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
