"""Add last_seen column on User

Revision ID: f4ed54a16655
Revises: 2dfb9cef20de
Create Date: 2021-07-29 19:36:26.529062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4ed54a16655"
down_revision = "2dfb9cef20de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), server_default=sa.text("now()"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    # ### end Alembic commands ###
